rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
  - jruby
gemfile:
  - ci/Gemfile.activerecord-4.1.x
  - ci/Gemfile.activerecord-4.0.x
  - ci/Gemfile.activerecord-3.2.x
  - ci/Gemfile.activerecord-3.1.x
  - ci/Gemfile.activerecord-3.0.x
